name: Deploy from GHCR to AWS EC2

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ghcr.io/satyanarayana-zemoso/bootcamp26-app-backend:v${{ github.run_number }}
          dockerfile: Dockerfile


      - name: SSH into remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BOOTCAMP_EC2_KEY }} 
          RUN_NUMBER: ${{ github.run_number }}
          AWS_DNS : ${{ secrets.AWS_BACKEND_DNS }}
          USERNAME: ${{ github.actor }}
          PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/ssh_private_key
          chmod 400 ~/ssh_private_key
          ssh -i ~/ssh_private_key -o StrictHostKeyChecking=no ubuntu@$AWS_DNS "
            docker login ghcr.io -u $USERNAME --password $PAT;
            docker stop $(sudo docker ps -aq);
            docker rmi $(sudo docker images -q);
            docker run -d -p 8090:8090 ghcr.io/satyanarayana-zemoso/bootcamp26-app-backend:v$RUN_NUMBER;
            docker logout ghcr.io;
            "
            rm -rf ~/ssh_private_key
          

