name: build mysql image and push to ghcr.io and deploy in ec2
on:
  push:
    paths:
      - '.github/workflows/database.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: database
        
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_PAT }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./database
        push: true
        tags: ghcr.io/satyanarayana-zemoso/bootcamp26-app-database:v${{ github.run_number }}


    - name: SSH into remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.BOOTCAMP_EC2_KEY }} 
        RUN_NUMBER: ${{ github.run_number }}
        AWS_DNS : ${{ secrets.AWS_DATABASE_DNS}}
        USERNAME: ${{ github.actor }}
        PAT: ${{ secrets.GIT_PAT }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/ssh_private_key
        chmod 400 ~/ssh_private_key
        ssh -i ~/ssh_private_key -o StrictHostKeyChecking=no ubuntu@$AWS_DNS "
            docker login ghcr.io -u $USERNAME --password $PAT;
            docker stop $(docker ps -aq);
            docker rmi $(docker images -q);
            docker pull ghcr.io/satyanarayana-zemoso/bootcamp26-app-database:v$RUN_NUMBER;
            docker run --name database -d -p 3306:3306  -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} ghcr.io/satyanarayana-zemoso/bootcamp26-app-database:v$RUN_NUMBER;
            docker logout ghcr.io;
        "
        rm -rf ~/ssh_private_key
        










