name: deploy mock server to ghcr and ec2

on:
  push:
    paths:
      - 'rontend/src/mockData/**'
      - '.github/workflows/mock-server.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run: 
        working-directory: frontend/src/mockData
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/src/mockData
          push: true
          tags: ghcr.io/${{ github.actor }}/bootcamp26-app-mockServer:v${{ github.run_number }}

      - name: SSH into remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BOOTCAMP_EC2_KEY }} 
          RUN_NUMBER: ${{ github.run_number }}
          AWS_DNS : ${{ secrets.AWS_FRONTEND_DNS}}
          USERNAME: ${{ github.actor }}
          PAT: ${{ secrets.GIT_PAT }}
        run: |
            echo "$SSH_PRIVATE_KEY" > ~/ssh_private_key
            chmod 400 ~/ssh_private_key
            ssh -i ~/ssh_private_key -o StrictHostKeyChecking=no ubuntu@$AWS_DNS "
                docker login ghcr.io -u $USERNAME --password $PAT;
                docker stop mockserver 2>/dev/null;
                docker rm mockserver 2>/dev/null;
                docker run -d -p 3001:3001 --name mockserver ghcr.io/satyanarayana-zemoso/bootcamp26-app-mockserver:v$RUN_NUMBER;
                docker logout ghcr.io;
            "
            rm -rf ~/ssh_private_key



            

      